name: emotions
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  fluttertoast: ^8.2.12
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.3
  firebase_messaging: ^15.2.5
  home_widget: ^0.7.0+1
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/backgrounds/
    - lib/assets/single/
    - lib/assets/skins/default/
    - lib/assets/skins/sleep/
    - lib/assets/icons/
  fonts:
    - family: 'AmaticSC'
      fonts:
        - asset: lib/assets/fonts/AmaticSC-Bold.ttf
          weight: 700